name = "jangoing-api"
main = "src/index.ts"
compatibility_date = "2025-02-14"

[vars]
AUTH_REQUIRED = "false"
APP_JWT_ISSUER = "jangoing-web"
APP_JWT_AUDIENCE = "jangoing-api"

[[d1_databases]]
binding = "DB"
database_name = "jangoing-db"
database_id = "017287d7-6fff-4793-80d0-1963d23de934"
migrations_dir = "migrations"
